nkpx2e : global.o nkdynp.o file_man.o
	g++ -Wall global.o nkdynp.o file_man.o -o nkdynpe

global.o : global.cpp	
	g++ -Wall -o global.o -c global.cpp

nkpx2.o : nkpx2.cpp	
	g++ -Wall -o nkdynp.o -c nkdynp.cpp

file_man.o : file_man.cpp	
	g++ -Wall -o file_man.o -c file_man.cpp