NNcommitteee : global.o NNcommittee.o util_functions.o file_man.o	
	g++ -Wall global.o NNcommittee.o util_functions.o file_man.o -o NNcommitteee

global.o : global.cpp	
	g++ -Wall -o global.o -c global.cpp

NNcommittee.o : NNcommittee.cpp	
	g++ -Wall -o NNcommittee.o -c NNcommittee.cpp

util_functions.o : util_functions.cpp	
	g++ -Wall -o util_functions.o -c util_functions.cpp

file_man.o : file_man.cpp	
	g++ -Wall -o file_man.o -c file_man.cpp


