mv ./k2/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k2/regular;
mv ./k3/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k3/regular;
mv ./k4/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k4/regular;
mv ./k5/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k5/regular;
mv ./k6/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k6/regular;
mv ./k7/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k7/regular;
mv ./k8/regular/*.dat ./data;
time ./nkdynpe;
mv ./data/*.dat ./k8/regular;