nnet2nke : global.o nnet2nk.o util_functions.o file_man.o	
	g++ -Wall global.o nnet2nk.o util_functions.o file_man.o -o nnet2nke

global.o : global.cpp	
	g++ -Wall -o global.o -c global.cpp

nnet2nk.o : nnet2nk.cpp	
	g++ -Wall -o nnet2nk.o -c nnet2nk.cpp

util_functions.o : util_functions.cpp	
	g++ -Wall -o util_functions.o -c util_functions.cpp

file_man.o : file_man.cpp	
	g++ -Wall -o file_man.o -c file_man.cpp


